### ISSUE TITLE
Remove obsolete zone version

### ISSUE THREAD

**Issue by alexbinary** [Marsup/gandynode#1]
I don't know about other people, but I don't like to see my Gandi dashboard full of obsolete zone versions. I would like gandynode to remove the previous active version after the new version is activated. This behavior could be enabled or disabled in the configuration file.
What do you think ?

**Comment by Marsup** [comment]
While I agree, it's hard to track which zone was created and which one was already there before the program ran, I don't think I can "tag" zones versions.

**Comment by alexbinary** [comment]
Thanks for your response. I may be missing something here, but wouldn't it possible to do the following :
1. get the current active zone version number (say it is 42)
2. create the new version, update the data and activate this version
3. remove version 42

?

I forked your repo with the intent of doing a pull request which implements that behavior, but couldn't figure out how to run gandynode from source. Can you provide some instructions ?

**Comment by Marsup** [comment]
I didn't do that because I don't like deleting what I don't own, and I don't see any way to know that. But I'm open to a PR adding a configuration to explicitly enable that.

You have to run `npm run build` then `bin/gandynode`.

**Comment by alexbinary** [comment]
Thanks for your help. I just did the pull request.
